APC/main/routes.py
import os


import pdfkit
import secrets
from PIL import Image
from flask import Blueprint, render_template, make_response, redirect, session, request, flash, url_for
from flask_login import login_required, current_user, login_user, logout_user


from APC.model import User
from APC.forms import LoginForm, RegisterForm, UploadImageForm
from APC import db, bcrypt

main = Blueprint('main', __name__)


def save_picture(form_picture):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_picture.filename)
    picture_fn = random_hex + f_ext
    picture_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '../static/images/profile_pictures', picture_fn)
    size=(180,180)
    f = Image.open(form_picture)
    f.thumbnail(size)
    f.save(picture_path)
    return picture_fn


@main.route('/print/')
@login_required
def pdf_template():
    phone = current_user.phone
    user = User.query.filter_by(phone=phone).first()
    if user.image == 'default_profile.jpg':
        return redirect(url_for('main.index'))
    host = request.host
    rendered = render_template('pdfcontent2.html', user=user, host=host)
    pdf = pdfkit.from_string(rendered, False)

    response = make_response(pdf)
    response.headers["Content-Type"] = "application/pdf"
    response.headers["Content-Disposition"] = "inline; filename=output.pdf"
    return response



@main.route('/test/')
@login_required
def card2():
    phone = current_user.phone
    user = User.query.filter_by(phone=phone).first()
    host = request.host
    return render_template('pdfcontent2.html', user=user, host=host)
    


# @main.route('/profile/')
# @login_required
# def card():
#     user_id = current_user.get_id()
#     form = UploadImageForm()
#     user = User.query.filter_by(id=user_id).first()
#     return render_template('index.html', user=user, form=form)


@main.route('/card/', methods=['GET','POST'])
@login_required
def index():
    if current_user.role == 'admin' or current_user.role == 'super':    
        return redirect('/admin/')
    alert = None
    user_id = current_user.get_id()
    user = User.query.filter_by(id=user_id).first()
    form = UploadImageForm()
    if request.method == 'POST':
        if form.validate() and form.validate_on_submit():
            if form.profile_image.data:
                picture_file = save_picture(form.profile_image.data)
                user.image = picture_file
                db.session.commit()
                flash('Your Image has been uploaded', 'info')
                return redirect(request.referrer)
        else:
            flash('Your Image was not uploaded', 'danger')
            return redirect(request.referrer)
    if user.image == 'default_profile.jpg':
        alert = 'Upload your picture before you can print'
    return render_template('card.html', user=user, form=form, alert=alert)





@main.route('/register/', methods=['GET','POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegisterForm()
    if form.validate_on_submit():
        user = User.query.filter_by(phone=form.phone.data).first()
        if user:
            flash('User already exists', 'info')
            return render_template('securtity/register_user.html', form=form)
        
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(firstname=form.firstname.data, lastname=form.lastname.data ,phone=form.phone.data, \
            sex=form.sex.data, state=form.state.data, ward=form.ward.data, role='user',\
            city=form.city.data, lga=form.lga.data , password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash("You have successfully registered!", 'info')
        login_user(user)
        return redirect(url_for('main.index'))
    return render_template('security/register_user.html', form=form, title='Register APC')



@main.route('/logout/')
@login_required
def logout():
    """
    Log Out User
    """
    logout_user()
    return redirect(url_for('main.login'))


@main.route('/', methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(phone=form.phone.data).first()
        if user:
			# password authentication
            if user and bcrypt.check_password_hash(user.password, form.password.data):
                if form.remember.data == True:
                    login_user(user, remember=True)
                else:
                    login_user(user)
                next_page = request.args.get('next')
                return redirect(next_page) if next_page else redirect(url_for('main.index'))
            else:
                flash("Invalid username/password.", 'danger')
        else:
            flash("Invalid username/password.", 'danger')
    return render_template('security/login_user.html', form=form, title='Login APC')






APC/templates/security/_macros.html
{% macro render_field_with_errors(field, description=None) %}
    
    {% if not field.errors %}
        <div class="form-group">
            <label for="{{ field.id }}"><strong>{{ field.label }}</strong></label>
            {% if description != None %}
                {{ field(class='form-control', placeholder=description, **kwargs) | safe }}
            {% else %}
                {{ field(class='form-control', **kwargs) | safe }}
            {% endif %}
        </div>
    {% else %}
        <div class="form-group">
            <label for="{{ field.id }}"><strong>{{ field.label }}</strong></label>
            {% if description != None %}
                {{ field(class='form-control is-invalid', placeholder=description, **kwargs) | safe }}
            {% else %}
                {{ field(class='form-control is-invalid', **kwargs) | safe }}
            {% endif %}
            {% for error in field.errors %}
            <div id="{{ field.id }}" class='invalid-feedback'>
                {{ error }}
            </div>
            {% endfor %}
            
        </div>
        
    {% endif %}
    

{% endmacro %}


{% macro render_shortfield_with_errors(field, field2) %}
    <div class="form-row">
        {% if not field.errors %}
            <div class="form-group col-md-6">
            <label for="{{ field.id }}"><strong>{{ field.label }}</strong></label>
                {{ field(class='form-control', **kwargs) | safe }}
            </div>
        {% else %}
            <div class="form-group col-md-6">
            <label for="{{ field.id }}"><strong>{{ field.label }}</strong></label>
                {{ field(class='form-control is-invalid', **kwargs) | safe }}
                {% for error in field.errors %}
                <div id="{{ field.id }}" class='invalid-feedback'>
                {{ error }}
                </div>
            {% endfor %}
            </div>
    {% endif %}
        
    {% if not field2.errors %}
        <div class="form-group col-md-6">
        <label for="{{ field.id }}"><strong>{{ field2.label }}</strong></label>
            {{ field2(class='form-control', **kwargs) | safe }}
        </div>
    {% else %}
        <div class="form-group col-md-6">
        <label for="{{ field.id }}"><strong>{{ field2.label }}</strong></label>
        {{ field2(class='form-control is-invalid', **kwargs) | safe }}
            {% for error in field2.errors %}
            <div id="{{ field2.id }}" class='invalid-feedback'>
                {{ error }}
            </div>
            {% endfor %}
        </div>
    {% endif %}
    </div>
    


{% endmacro %}


{% macro admin_view_input(field) %}
    {% if not field.errors %}
        {{ field(class='form-control', placeholder=description, **kwargs) | safe }}
    {% else %}
        {{ field(class='form-control is-invalid', placeholder=description, **kwargs) | safe }}
        {% for error in field.errors %}
            <div id="{{ field.id }}" class='invalid-feedback'>
                {{ error }}
            </div>
        {% endfor %}
    {% endif %}
{% endmacro %}


{% macro render_field(field) %}
    {{ field(class_='form-control', **kwargs)|safe }}
    {% if field.errors %}
        <ul>
            {%for error in field.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endmacro %}


{% macro render_image(field) %}
    <div class="form-group mb-3">
        <div class="custom-file">
            {{ field(class='custom-file-input', oninput='input_filename()', id="file_input", **kwargs) | safe }}
            <label for="file_input" id='file_input_label' class='custom-file-label'> {{ field.label }}</label>

            {% if field.errors %}
                <ul>
                {% for error in field.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
{% endmacro %}

{% macro render_checkbox_field(field) -%}
<div class="form-group">
    <div class="checkbox">
        <label>
            {{ field(type='checkbox', **kwargs) }} {{ field.label }}
        </label>
    </div>
</div>
{%- endmacro %}

APC/templates/security/forgot_password.html
{% from 'security/_macros.html' import render_field_with_errors, render_checkbox_field, render_field %}
{% extends 'site-templates/header2.html' %}

    {% block body %}
    <div class="card-content transition-fade" id='swup'>
        <div class="image-logo text-center">
            <img src="/static/images/logo.png" alt="Apc Logo" width="100" height="100">
        </div>
        <h1 class='text-center'>APC MEMBERSHIP RESET</h1>
        <form action="{{ url_for_security('forgot_password') }}" method="POST" name="forgot_password_form">
            {{ forgot_password_form.hidden_tag() }}
            {{ render_field_with_errors(forgot_password_form.email) }}
            {{ render_field(forgot_password_form.submit, class="btn btn-primary") }}
        </form>
        
        <p style='margin-top: 20px;'>Not yet signed up? Please <a href="{{ url_for_security('register') }}">register for an account</a>.</p>
        {% if security.recoverable %}
            <p><a href="{{ url_for_security('forgot_password') }}">Forgot password?</a></p>
        {% endif %}
    </div>
    

    {% endblock body %}

APC/templates/security/login_user.html
{% from 'security/_macros.html' import render_field_with_errors, render_checkbox_field, render_field %}
{% extends 'site-templates/header2.html' %}

    {% block body %}
    <div class="card-content transition-fade" id='swup'>
        <div class="image-logo text-center">
            <img src="/static/images/logo.png" alt="Apc Logo" width="100" height="100">
        </div>
        <h1 class='text-center'>ALL PROGRESSIVE CONGRESS</h1>
        <h1 class='text-center'>EKITI CHAPTER</h1>
        <form action="" method="POST" name="login_user_form" style='margin-top: 2.5rem;'>
            {{ form.hidden_tag() }}
            {{ render_field_with_errors(form.phone) }}
            {{ render_field_with_errors(form.password) }}
            {{ render_checkbox_field(form.remember) }}
            {{ render_field(form.submit, class="btn btn-primary") }}
        </form>
        
        <p style='margin-top: 20px;'>Not yet signed up? Please <a href="{{ url_for('main.register') }}">register for an account</a>.</p>
        
        
    </div>
    {% endblock body %}

    {% block scripts %}
    {{ super() }}
    <script>
        var phone_field = document.getElementById('phone');
        
        phone_field.addEventListener('focusout', ()=>{
                console.log('Running')
                var data = phone_field.value;
                if (data.startsWith('0')){
                    phone_field.value = data.replace('0', '+234');
                }
                else if (!data.startsWith('+234')){
                    phone_field.value = '+234' + data
                }
            }
        )

        // wtf_phone_field.style.position = 'absolute';
        // wtf_phone_field.style.top = '-9999px';
        // wtf_phone_field.style.left = '-9999px';
        // wtf_phone_field.parentElement.insertAdjacentHTML('beforeend', '<div><input type="tel" id="_phone" class="form-control"></div>');
        // var fancy_phone_field = document.getElementById('_phone');
        // var fancy_phone_iti = window.intlTelInput(fancy_phone_field, {
        //     separateDialCode: true,
        //     utilsScript: "https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/16.0.4/js/utils.js",
        // });
        // fancy_phone_iti.setNumber(wtf_phone_field.value);
        // fancy_phone_field.addEventListener('blur', function() {
        //     wtf_phone_field.value = fancy_phone_iti.getNumber();
        // });
    </script>
    {% endblock %}

APC/templates/security/register_user.html
{% from 'security/_macros.html' import render_field_with_errors, render_image, render_shortfield_with_errors, render_field %}
{% extends 'site-templates/header2.html' %}


        {% block body %}
        <div class="card-content transition-fade" id='swup'>
            <div class="image-logo text-center">
                <img src="/static/images/logo.png" alt="Apc Logo" width="100" height="100">
            </div>
            <h1 class='text-center'>ALL PROGRESSIVE CONGRESS</h1>
            <h1 class='text-center'>EKITI CHAPTER</h1>
            <form action="" method='POST' name='register_user_form' enctype="multipart/form-data" style='margin-top: 2.5rem;'>
                {{ form.hidden_tag() }}
                {{ render_shortfield_with_errors(form.firstname, form.lastname) }}
                
                {{ render_field_with_errors(form.sex) }}
                {{ render_shortfield_with_errors(form.state, form.city) }}
                
                {{ render_field_with_errors(form.lga) }}
                {{ render_field_with_errors(form.ward) }}
                {{ render_field_with_errors(form.phone, description='+234 80 123 45 678') }}
                {{ render_field_with_errors(form.password) }}
                
                {{ render_field_with_errors(form.confirm_password)}}
                {{ render_field(form.submit, class="btn btn-primary") }}
            </form>
            <p>Already Signed Up? Please <a href="{{ url_for('main.login') }}">Log In</a>.</p>
        </div>
                        

    {% endblock body %}
        
    {% block scripts %}
    {{ super() }}
    <script>
        var phone_field = document.getElementById('phone');
        
        phone_field.addEventListener('focusout', ()=>{
                console.log('Running')
                var data = phone_field.value;
                if (data.startsWith('0')){
                    phone_field.value = data.replace('0', '+234');
                }
                else if (!data.startsWith('+234')){
                    phone_field.value = '+234' + data
                }
            }
        )

        // wtf_phone_field.style.position = 'absolute';
        // wtf_phone_field.style.top = '-9999px';
        // wtf_phone_field.style.left = '-9999px';
        // wtf_phone_field.parentElement.insertAdjacentHTML('beforeend', '<div><input type="tel" id="_phone" class="form-control"></div>');
        // var fancy_phone_field = document.getElementById('_phone');
        // var fancy_phone_iti = window.intlTelInput(fancy_phone_field, {
        //     separateDialCode: true,
        //     utilsScript: "https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/16.0.4/js/utils.js",
        // });
        // fancy_phone_iti.setNumber(wtf_phone_field.value);
        // fancy_phone_field.addEventListener('blur', function() {
        //     wtf_phone_field.value = fancy_phone_iti.getNumber();
        // });
    </script>
    {% endblock %}